### ISSUE TITLE
🚀 Release 1.4.0

### ISSUE THREAD

**Issue by lucasilverentand** [onezerocompany/coding#142]
### Stable
 
```
Have a look at what we changed this time



Feature Improvements
- match runtime to devcontainer
```

- [ ] :next_track_button: Skipped changelog approval 
- [ ] :next_track_button: Release clearance was skipped 
- [ ] :hourglass_flowing_sand: Waiting for release creation
