### ISSUE TITLE
🚀 Release 1.3.2

### ISSUE THREAD

**Issue by lucasilverentand** [onezerocompany/coding#143]
### Stable
 
```
Take a look at what changes we made this time

This update contains minor improvements and fixes.
```

- [ ] :next_track_button: Skipped changelog approval 
- [ ] :next_track_button: Release clearance was skipped 
- [ ] :hourglass_flowing_sand: Waiting for release creation
