### ISSUE TITLE
Project Manager

### ISSUE THREAD

**Issue by lucasilverentand** [onezerocompany/coding#224]
Since we are maintaining numerous repos here at OneZero, we need a way to keep the configs in sync with our latest tooling. Having a project manager that can be used to check and update these tools and the project structures would be a great help.

```[tasklist]
### Tasks
- [ ] TypeScript based project manifest
- [ ] Project Manager GitHub Action
- [ ] project-manager cli tool
```
